### ISSUE TITLE
intermittent failure of TTAgent test

### ISSUE THREAD

**Issue by DrPaulBrewer** [DrPaulBrewer/market-agents#18]
Test failure message:
```
 1) new TTAgent
       specifying currentBid,currentAsk will produce bids/asks consistent with optimizing over flat prior:
     AssertionError: expected 200 to be below 200
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.below (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/index.js:900:38)
      at processImmediate (internal/timers.js:458:21)
```

refers to this code

https://github.com/DrPaulBrewer/market-agents/blob/deed082e8dd4389acf8eb4705f18a00879727e4f/test/index.js#L900

The test fails 16 out of 3193 times, which is close to 1 in 200.
The stddev of tests-to-failure is 189

This is consistent with a bid generated as U[1,200] yielding 200, which fails `.should.be.below(200)`

**Comment by DrPaulBrewer** [comment]
In line 900 all that is known is that the TTAgent should behave as a ZIAgent, and has a unit value of 200.

The test is incorrect, because it excludes 200.  The test should be .within(1,200) because L=1 and .within includes both 1 and 200.

**Comment by DrPaulBrewer** [comment]
After changing the line, and using more cases on the Poisson rate tests, the rate of failure of `npm test` is now down around
1 in 6000.  [Parallel testing on GCP c2-highcpu-16 overnight]. 

The remaining 'failures' are all low-occurrence random tests that are Poisson rate related, with statistics slightly outside an approximate 5 sigma test range.

Since these tests are random, and are designed so that failure is a low probability event, and since the transformations from Poisson to normal are approximate, this seems like a reasonable outcome.
